from .Rosenbrock import Rosenbrock
from .MinimalSurface import MinimalSurface
from .Madelon import Madelon
from .Huber import Huber
from .Denoising import Denoising
from .vonMises import vonMises
from .Tomography import Tomography
from .RadialBasis import RadialBasis
from .UCI_Classification import UCI_Classification
